version: "3"

services:
  bot:
    image: ghcr.io/holodata/bot:latest
    container_name: bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    extra_hosts:
      mongo: ${HB_MONGO_REAL_IP}
